# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stackedwid1.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from mongodb.utils import *
from functions import *

class UI(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(721, 613)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 0, 701, 571))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_0 = QtWidgets.QWidget()
        self.page_0.setObjectName("page_0")
        self.label_2 = QtWidgets.QLabel(self.page_0)
        self.label_2.setGeometry(QtCore.QRect(200, 260, 61, 31))
        self.label_2.setObjectName("label_2")
        self.lineEdit_pw_0 = QtWidgets.QLineEdit(self.page_0)
        self.lineEdit_pw_0.setGeometry(QtCore.QRect(260, 259, 141, 31))
        self.lineEdit_pw_0.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_pw_0.setObjectName("lineEdit_pw_0")
        self.btn_enter_0 = QtWidgets.QPushButton(self.page_0)
        self.btn_enter_0.setGeometry(QtCore.QRect(400, 260, 81, 31))
        self.btn_enter_0.setObjectName("btn_enter_0")
        self.stackedWidget.addWidget(self.page_0)
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.btn_go2Data_1 = QtWidgets.QPushButton(self.page_1)
        self.btn_go2Data_1.setGeometry(QtCore.QRect(250, 220, 151, 41))
        self.btn_go2Data_1.setObjectName("btn_go2Data_1")
        self.btn_go2Client_1 = QtWidgets.QPushButton(self.page_1)
        self.btn_go2Client_1.setGeometry(QtCore.QRect(250, 270, 151, 41))
        self.btn_go2Client_1.setObjectName("btn_go2Client_1")
        self.btn_logout_1 = QtWidgets.QPushButton(self.page_1)
        self.btn_logout_1.setGeometry(QtCore.QRect(530, 30, 113, 41))
        self.btn_logout_1.setObjectName("btn_logout_1")
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.btn_registerNewClient_2 = QtWidgets.QPushButton(self.page_2)
        self.btn_registerNewClient_2.setGeometry(QtCore.QRect(260, 230, 151, 41))
        self.btn_registerNewClient_2.setObjectName("btn_registerNewClient_2")
        self.btn_findExistingClient_2 = QtWidgets.QPushButton(self.page_2)
        self.btn_findExistingClient_2.setGeometry(QtCore.QRect(260, 280, 151, 41))
        self.btn_findExistingClient_2.setObjectName("btn_findExistingClient_2")
        self.label = QtWidgets.QLabel(self.page_2)
        self.label.setGeometry(QtCore.QRect(250, 190, 60, 16))
        self.label.setObjectName("label")
        self.btn_home_2 = QtWidgets.QPushButton(self.page_2)
        self.btn_home_2.setGeometry(QtCore.QRect(570, 20, 71, 51))
        self.btn_home_2.setObjectName("btn_home_2")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_3 = QtWidgets.QLabel(self.page_3)
        self.label_3.setGeometry(QtCore.QRect(40, 20, 151, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.page_3)
        self.label_4.setGeometry(QtCore.QRect(60, 50, 60, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.page_3)
        self.label_5.setGeometry(QtCore.QRect(60, 80, 60, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.page_3)
        self.label_6.setGeometry(QtCore.QRect(60, 110, 60, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.page_3)
        self.label_7.setGeometry(QtCore.QRect(60, 140, 60, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.page_3)
        self.label_8.setGeometry(QtCore.QRect(60, 170, 60, 21))
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.page_3)
        self.label_10.setGeometry(QtCore.QRect(60, 290, 60, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.page_3)
        self.label_11.setGeometry(QtCore.QRect(60, 200, 60, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.page_3)
        self.label_12.setGeometry(QtCore.QRect(60, 230, 60, 21))
        self.label_12.setObjectName("label_12")
        self.lineEdit_ID_3 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_ID_3.setGeometry(QtCore.QRect(160, 50, 113, 21))
        self.lineEdit_ID_3.setObjectName("lineEdit_ID_3")
        self.lineEdit_name_3 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_name_3.setGeometry(QtCore.QRect(160, 80, 113, 21))
        self.lineEdit_name_3.setObjectName("lineEdit_name_3")
        self.ckBox_preg_3 = QtWidgets.QCheckBox(self.page_3)
        self.ckBox_preg_3.setGeometry(QtCore.QRect(160, 260, 61, 20))
        self.ckBox_preg_3.setObjectName("ckBox_preg_3")
        self.ckBox_bFeeding_3 = QtWidgets.QCheckBox(self.page_3)
        self.ckBox_bFeeding_3.setGeometry(QtCore.QRect(220, 260, 61, 20))
        self.ckBox_bFeeding_3.setObjectName("ckBox_bFeeding_3")
        self.radioBtn_female_3 = QtWidgets.QRadioButton(self.page_3)
        self.radioBtn_female_3.setGeometry(QtCore.QRect(210, 110, 71, 20))
        self.radioBtn_female_3.setObjectName("radioBtn_female_3")
        self.radioBtn_male_3 = QtWidgets.QRadioButton(self.page_3)
        self.radioBtn_male_3.setGeometry(QtCore.QRect(160, 110, 51, 20))
        self.radioBtn_male_3.setChecked(True)
        self.radioBtn_male_3.setObjectName("radioBtn_male_3")
        self.lineEdit_height_3 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_height_3.setGeometry(QtCore.QRect(160, 200, 71, 21))
        self.lineEdit_height_3.setObjectName("lineEdit_height_3")
        self.dateEdit_birthdate_3 = QtWidgets.QDateEdit(self.page_3)
        self.dateEdit_birthdate_3.setGeometry(QtCore.QRect(160, 140, 110, 24))
        self.dateEdit_birthdate_3.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(1900, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit_birthdate_3.setMinimumDate(QtCore.QDate(1900, 1, 1))
        self.dateEdit_birthdate_3.setCalendarPopup(True)
        self.dateEdit_birthdate_3.setObjectName("dateEdit_birthdate_3")
        self.lineEdit_address_3 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_address_3.setGeometry(QtCore.QRect(160, 170, 301, 21))
        self.lineEdit_address_3.setObjectName("lineEdit_address_3")
        self.dateEdit_lastOfficeVisit_3 = QtWidgets.QDateEdit(self.page_3)
        self.dateEdit_lastOfficeVisit_3.setGeometry(QtCore.QRect(160, 290, 110, 24))
        self.dateEdit_lastOfficeVisit_3.setCalendarPopup(True)
        self.dateEdit_lastOfficeVisit_3.setObjectName("dateEdit_lastOfficeVisit_3")
        self.btn_home_3 = QtWidgets.QPushButton(self.page_3)
        self.btn_home_3.setGeometry(QtCore.QRect(570, 20, 71, 51))
        self.btn_home_3.setObjectName("btn_home_3")
        self.widget_13 = QtWidgets.QWidget(self.page_3)
        self.widget_13.setGeometry(QtCore.QRect(440, 510, 221, 61))
        self.widget_13.setObjectName("widget_13")
        self.btn_cancel_3 = QtWidgets.QPushButton(self.widget_13)
        self.btn_cancel_3.setGeometry(QtCore.QRect(10, 20, 101, 31))
        self.btn_cancel_3.setObjectName("btn_cancel_3")
        self.btn_next_3 = QtWidgets.QPushButton(self.widget_13)
        self.btn_next_3.setGeometry(QtCore.QRect(110, 20, 101, 31))
        self.btn_next_3.setObjectName("btn_next_3")
        self.btn_checkUniqID_3 = QtWidgets.QPushButton(self.page_3)
        self.btn_checkUniqID_3.setGeometry(QtCore.QRect(280, 50, 113, 32))
        self.btn_checkUniqID_3.setObjectName("btn_checkUniqID_3")
        self.label_13 = QtWidgets.QLabel(self.page_3)
        self.label_13.setGeometry(QtCore.QRect(240, 230, 60, 21))
        self.label_13.setObjectName("label_13")
        self.label_24 = QtWidgets.QLabel(self.page_3)
        self.label_24.setGeometry(QtCore.QRect(240, 200, 60, 21))
        self.label_24.setObjectName("label_24")
        self.lineEdit_weight_3 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_weight_3.setGeometry(QtCore.QRect(160, 230, 71, 21))
        self.lineEdit_weight_3.setObjectName("lineEdit_weight_3")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.widget_16 = QtWidgets.QWidget(self.page_4)
        self.widget_16.setGeometry(QtCore.QRect(-30, 0, 771, 511))
        self.widget_16.setObjectName("widget_16")
        self.listWidget_diseases_4 = QtWidgets.QListWidget(self.widget_16)
        self.listWidget_diseases_4.setGeometry(QtCore.QRect(30, 60, 161, 441))
        self.listWidget_diseases_4.setObjectName("listWidget_diseases_4")
        self.label_34 = QtWidgets.QLabel(self.widget_16)
        self.label_34.setGeometry(QtCore.QRect(100, 30, 60, 21))
        self.label_34.setObjectName("label_34")
        self.tableWidget_allergies_gs_4 = QtWidgets.QTableWidget(self.widget_16)
        self.tableWidget_allergies_gs_4.setGeometry(QtCore.QRect(200, 60, 171, 441))
        self.tableWidget_allergies_gs_4.setObjectName("tableWidget_allergies_gs_4")
        self.tableWidget_allergies_gs_4.setColumnCount(2)
        self.tableWidget_allergies_gs_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_allergies_gs_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_allergies_gs_4.setHorizontalHeaderItem(1, item)
        self.label_53 = QtWidgets.QLabel(self.widget_16)
        self.label_53.setGeometry(QtCore.QRect(240, 30, 101, 21))
        self.label_53.setObjectName("label_53")
        self.tableWidget_allergies_ms_4 = QtWidgets.QTableWidget(self.widget_16)
        self.tableWidget_allergies_ms_4.setGeometry(QtCore.QRect(380, 60, 171, 441))
        self.tableWidget_allergies_ms_4.setObjectName("tableWidget_allergies_ms_4")
        self.tableWidget_allergies_ms_4.setColumnCount(2)
        self.tableWidget_allergies_ms_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_allergies_ms_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_allergies_ms_4.setHorizontalHeaderItem(1, item)
        self.tableWidget_allergies_lgg4_4 = QtWidgets.QTableWidget(self.widget_16)
        self.tableWidget_allergies_lgg4_4.setGeometry(QtCore.QRect(560, 60, 171, 441))
        self.tableWidget_allergies_lgg4_4.setObjectName("tableWidget_allergies_lgg4_4")
        self.tableWidget_allergies_lgg4_4.setColumnCount(2)
        self.tableWidget_allergies_lgg4_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_allergies_lgg4_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_allergies_lgg4_4.setHorizontalHeaderItem(1, item)
        self.label_80 = QtWidgets.QLabel(self.widget_16)
        self.label_80.setGeometry(QtCore.QRect(420, 30, 101, 21))
        self.label_80.setObjectName("label_80")
        self.label_81 = QtWidgets.QLabel(self.widget_16)
        self.label_81.setGeometry(QtCore.QRect(580, 30, 131, 21))
        self.label_81.setObjectName("label_81")
        self.widget_17 = QtWidgets.QWidget(self.page_4)
        self.widget_17.setGeometry(QtCore.QRect(390, 500, 311, 61))
        self.widget_17.setObjectName("widget_17")
        self.btn_cancel_4 = QtWidgets.QPushButton(self.widget_17)
        self.btn_cancel_4.setGeometry(QtCore.QRect(0, 20, 101, 31))
        self.btn_cancel_4.setObjectName("btn_cancel_4")
        self.btn_registerClient_4 = QtWidgets.QPushButton(self.widget_17)
        self.btn_registerClient_4.setGeometry(QtCore.QRect(200, 20, 101, 31))
        self.btn_registerClient_4.setObjectName("btn_registerClient_4")
        self.btn_back_4 = QtWidgets.QPushButton(self.widget_17)
        self.btn_back_4.setGeometry(QtCore.QRect(100, 20, 101, 31))
        self.btn_back_4.setObjectName("btn_back_4")
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.label_38 = QtWidgets.QLabel(self.page_5)
        self.label_38.setGeometry(QtCore.QRect(50, 30, 101, 21))
        self.label_38.setObjectName("label_38")
        self.label_27 = QtWidgets.QLabel(self.page_5)
        self.label_27.setGeometry(QtCore.QRect(60, 70, 60, 31))
        self.label_27.setObjectName("label_27")
        self.lineEdit_ID_5 = QtWidgets.QLineEdit(self.page_5)
        self.lineEdit_ID_5.setGeometry(QtCore.QRect(170, 70, 131, 31))
        self.lineEdit_ID_5.setObjectName("lineEdit_ID_5")
        self.btn_findbyID_5 = QtWidgets.QPushButton(self.page_5)
        self.btn_findbyID_5.setGeometry(QtCore.QRect(310, 70, 111, 31))
        self.btn_findbyID_5.setObjectName("btn_findbyID_5")
        self.lineEdit_name_5 = QtWidgets.QLineEdit(self.page_5)
        self.lineEdit_name_5.setGeometry(QtCore.QRect(170, 160, 131, 31))
        self.lineEdit_name_5.setObjectName("lineEdit_name_5")
        self.label_30 = QtWidgets.QLabel(self.page_5)
        self.label_30.setGeometry(QtCore.QRect(60, 160, 101, 20))
        self.label_30.setObjectName("label_30")
        self.btn_findbyName_5 = QtWidgets.QPushButton(self.page_5)
        self.btn_findbyName_5.setGeometry(QtCore.QRect(310, 160, 111, 31))
        self.btn_findbyName_5.setObjectName("btn_findbyName_5")
        self.tableWidget_clientCandidates_5 = QtWidgets.QTableWidget(self.page_5)
        self.tableWidget_clientCandidates_5.setGeometry(QtCore.QRect(50, 240, 421, 291))
        self.tableWidget_clientCandidates_5.setObjectName("tableWidget_clientCandidates_5")
        self.tableWidget_clientCandidates_5.setColumnCount(4)
        self.tableWidget_clientCandidates_5.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_clientCandidates_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_clientCandidates_5.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_clientCandidates_5.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_clientCandidates_5.setHorizontalHeaderItem(3, item)
        self.btn_home_5 = QtWidgets.QPushButton(self.page_5)
        self.btn_home_5.setGeometry(QtCore.QRect(570, 20, 71, 51))
        self.btn_home_5.setObjectName("btn_home_5")
        self.widget_14 = QtWidgets.QWidget(self.page_5)
        self.widget_14.setGeometry(QtCore.QRect(440, 510, 221, 61))
        self.widget_14.setObjectName("widget_14")
        self.btn_cancel_5 = QtWidgets.QPushButton(self.widget_14)
        self.btn_cancel_5.setGeometry(QtCore.QRect(10, 20, 101, 31))
        self.btn_cancel_5.setObjectName("btn_cancel_5")
        self.btn_confirmClient_5 = QtWidgets.QPushButton(self.widget_14)
        self.btn_confirmClient_5.setGeometry(QtCore.QRect(110, 20, 101, 31))
        self.btn_confirmClient_5.setObjectName("btn_confirmClient_5")
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.label_31 = QtWidgets.QLabel(self.page_6)
        self.label_31.setGeometry(QtCore.QRect(30, 20, 151, 21))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.page_6)
        self.label_32.setGeometry(QtCore.QRect(40, 170, 60, 21))
        self.label_32.setObjectName("label_32")
        self.label_41 = QtWidgets.QLabel(self.page_6)
        self.label_41.setGeometry(QtCore.QRect(40, 290, 60, 16))
        self.label_41.setObjectName("label_41")
        self.radioBtn_female_6 = QtWidgets.QRadioButton(self.page_6)
        self.radioBtn_female_6.setGeometry(QtCore.QRect(190, 110, 71, 20))
        self.radioBtn_female_6.setObjectName("radioBtn_female_6")
        self.label_37 = QtWidgets.QLabel(self.page_6)
        self.label_37.setGeometry(QtCore.QRect(40, 200, 60, 21))
        self.label_37.setObjectName("label_37")
        self.radioBtn_male_6 = QtWidgets.QRadioButton(self.page_6)
        self.radioBtn_male_6.setGeometry(QtCore.QRect(140, 110, 51, 20))
        self.radioBtn_male_6.setObjectName("radioBtn_male_6")
        self.label_39 = QtWidgets.QLabel(self.page_6)
        self.label_39.setGeometry(QtCore.QRect(40, 80, 60, 21))
        self.label_39.setObjectName("label_39")
        self.dateEdit_lastOfficeVisit_6 = QtWidgets.QDateEdit(self.page_6)
        self.dateEdit_lastOfficeVisit_6.setGeometry(QtCore.QRect(140, 290, 110, 24))
        self.dateEdit_lastOfficeVisit_6.setObjectName("dateEdit_lastOfficeVisit_6")
        self.ckBox_preg_6 = QtWidgets.QCheckBox(self.page_6)
        self.ckBox_preg_6.setGeometry(QtCore.QRect(140, 260, 61, 20))
        self.ckBox_preg_6.setObjectName("ckBox_preg_6")
        self.ckBox_bFeeding_6 = QtWidgets.QCheckBox(self.page_6)
        self.ckBox_bFeeding_6.setGeometry(QtCore.QRect(200, 260, 61, 20))
        self.ckBox_bFeeding_6.setObjectName("ckBox_bFeeding_6")
        self.lineEdit_address_6 = QtWidgets.QLineEdit(self.page_6)
        self.lineEdit_address_6.setGeometry(QtCore.QRect(140, 170, 301, 21))
        self.lineEdit_address_6.setObjectName("lineEdit_address_6")
        self.lineEdit_ID_6 = QtWidgets.QLineEdit(self.page_6)
        self.lineEdit_ID_6.setGeometry(QtCore.QRect(140, 50, 113, 21))
        self.lineEdit_ID_6.setReadOnly(True)
        self.lineEdit_ID_6.setObjectName("lineEdit_ID_6")
        self.lineEdit_name_6 = QtWidgets.QLineEdit(self.page_6)
        self.lineEdit_name_6.setGeometry(QtCore.QRect(140, 80, 113, 21))
        self.lineEdit_name_6.setObjectName("lineEdit_name_6")
        self.label_40 = QtWidgets.QLabel(self.page_6)
        self.label_40.setGeometry(QtCore.QRect(40, 140, 60, 21))
        self.label_40.setObjectName("label_40")
        self.dateEdit_birthdate_6 = QtWidgets.QDateEdit(self.page_6)
        self.dateEdit_birthdate_6.setGeometry(QtCore.QRect(140, 140, 110, 24))
        self.dateEdit_birthdate_6.setObjectName("dateEdit_birthdate_6")
        self.lineEdit_height_6 = QtWidgets.QLineEdit(self.page_6)
        self.lineEdit_height_6.setGeometry(QtCore.QRect(140, 200, 71, 21))
        self.lineEdit_height_6.setObjectName("lineEdit_height_6")
        self.label_36 = QtWidgets.QLabel(self.page_6)
        self.label_36.setGeometry(QtCore.QRect(40, 50, 60, 21))
        self.label_36.setObjectName("label_36")
        self.label_35 = QtWidgets.QLabel(self.page_6)
        self.label_35.setGeometry(QtCore.QRect(40, 230, 60, 21))
        self.label_35.setObjectName("label_35")
        self.label_42 = QtWidgets.QLabel(self.page_6)
        self.label_42.setGeometry(QtCore.QRect(40, 110, 60, 21))
        self.label_42.setObjectName("label_42")
        self.btn_home_6 = QtWidgets.QPushButton(self.page_6)
        self.btn_home_6.setGeometry(QtCore.QRect(570, 20, 71, 51))
        self.btn_home_6.setObjectName("btn_home_6")
        self.widget_15 = QtWidgets.QWidget(self.page_6)
        self.widget_15.setGeometry(QtCore.QRect(350, 510, 311, 61))
        self.widget_15.setObjectName("widget_15")
        self.btn_cancel_6 = QtWidgets.QPushButton(self.widget_15)
        self.btn_cancel_6.setGeometry(QtCore.QRect(10, 20, 101, 31))
        self.btn_cancel_6.setObjectName("btn_cancel_6")
        self.btn_save_6 = QtWidgets.QPushButton(self.widget_15)
        self.btn_save_6.setGeometry(QtCore.QRect(110, 20, 101, 31))
        self.btn_save_6.setObjectName("btn_save_6")
        self.btn_save_next_6 = QtWidgets.QPushButton(self.widget_15)
        self.btn_save_next_6.setGeometry(QtCore.QRect(210, 20, 101, 31))
        self.btn_save_next_6.setObjectName("btn_save_next_6")
        self.label_56 = QtWidgets.QLabel(self.page_6)
        self.label_56.setGeometry(QtCore.QRect(220, 200, 60, 21))
        self.label_56.setObjectName("label_56")
        self.label_79 = QtWidgets.QLabel(self.page_6)
        self.label_79.setGeometry(QtCore.QRect(220, 230, 60, 21))
        self.label_79.setObjectName("label_79")
        self.lineEdit_weight_6 = QtWidgets.QLineEdit(self.page_6)
        self.lineEdit_weight_6.setGeometry(QtCore.QRect(140, 230, 71, 21))
        self.lineEdit_weight_6.setObjectName("lineEdit_weight_6")
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.widget = QtWidgets.QWidget(self.page_7)
        self.widget.setGeometry(QtCore.QRect(0, 0, 661, 561))
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 571, 81))
        self.widget_2.setObjectName("widget_2")
        self.lineEdit_name_7 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_name_7.setGeometry(QtCore.QRect(60, 10, 113, 21))
        self.lineEdit_name_7.setReadOnly(True)
        self.lineEdit_name_7.setObjectName("lineEdit_name_7")
        self.label_14 = QtWidgets.QLabel(self.widget_2)
        self.label_14.setGeometry(QtCore.QRect(30, 10, 60, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.widget_2)
        self.label_15.setGeometry(QtCore.QRect(190, 10, 60, 16))
        self.label_15.setObjectName("label_15")
        self.lineEdit_ID_7 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_ID_7.setGeometry(QtCore.QRect(210, 10, 113, 21))
        self.lineEdit_ID_7.setReadOnly(True)
        self.lineEdit_ID_7.setObjectName("lineEdit_ID_7")
        self.label_16 = QtWidgets.QLabel(self.widget_2)
        self.label_16.setGeometry(QtCore.QRect(330, 10, 60, 21))
        self.label_16.setObjectName("label_16")
        self.lineEdit_age_7 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_age_7.setGeometry(QtCore.QRect(500, 10, 41, 21))
        self.lineEdit_age_7.setReadOnly(True)
        self.lineEdit_age_7.setObjectName("lineEdit_age_7")
        self.lineEdit_weight_7 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_weight_7.setGeometry(QtCore.QRect(460, 40, 51, 21))
        self.lineEdit_weight_7.setReadOnly(True)
        self.lineEdit_weight_7.setObjectName("lineEdit_weight_7")
        self.label_17 = QtWidgets.QLabel(self.widget_2)
        self.label_17.setGeometry(QtCore.QRect(30, 40, 60, 21))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.widget_2)
        self.label_18.setGeometry(QtCore.QRect(240, 40, 60, 21))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.widget_2)
        self.label_19.setGeometry(QtCore.QRect(550, 10, 60, 21))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.widget_2)
        self.label_20.setGeometry(QtCore.QRect(420, 40, 60, 21))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.widget_2)
        self.label_21.setGeometry(QtCore.QRect(310, 40, 60, 21))
        self.label_21.setObjectName("label_21")
        self.lineEdit_height_7 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_height_7.setGeometry(QtCore.QRect(330, 40, 51, 21))
        self.lineEdit_height_7.setReadOnly(True)
        self.lineEdit_height_7.setObjectName("lineEdit_height_7")
        self.lineEdit_nthVisit_7 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_nthVisit_7.setGeometry(QtCore.QRect(190, 40, 41, 21))
        self.lineEdit_nthVisit_7.setReadOnly(True)
        self.lineEdit_nthVisit_7.setObjectName("lineEdit_nthVisit_7")
        self.lineEdit_birthdate_7 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_birthdate_7.setGeometry(QtCore.QRect(380, 10, 113, 21))
        self.lineEdit_birthdate_7.setReadOnly(True)
        self.lineEdit_birthdate_7.setObjectName("lineEdit_birthdate_7")
        self.lineEdit_lastOfficeVisit_7 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_lastOfficeVisit_7.setGeometry(QtCore.QRect(70, 40, 113, 21))
        self.lineEdit_lastOfficeVisit_7.setReadOnly(True)
        self.lineEdit_lastOfficeVisit_7.setObjectName("lineEdit_lastOfficeVisit_7")
        self.label_73 = QtWidgets.QLabel(self.widget_2)
        self.label_73.setGeometry(QtCore.QRect(380, 40, 60, 21))
        self.label_73.setObjectName("label_73")
        self.label_86 = QtWidgets.QLabel(self.widget_2)
        self.label_86.setGeometry(QtCore.QRect(510, 40, 60, 21))
        self.label_86.setObjectName("label_86")
        self.btn_home_7 = QtWidgets.QPushButton(self.widget)
        self.btn_home_7.setGeometry(QtCore.QRect(570, 20, 71, 51))
        self.btn_home_7.setObjectName("btn_home_7")
        self.widget_18 = QtWidgets.QWidget(self.widget)
        self.widget_18.setGeometry(QtCore.QRect(0, 80, 681, 451))
        self.widget_18.setObjectName("widget_18")
        self.listWidget_diseases_7 = QtWidgets.QListWidget(self.widget_18)
        self.listWidget_diseases_7.setGeometry(QtCore.QRect(0, 40, 151, 391))
        self.listWidget_diseases_7.setObjectName("listWidget_diseases_7")
        self.label_82 = QtWidgets.QLabel(self.widget_18)
        self.label_82.setGeometry(QtCore.QRect(60, 10, 60, 21))
        self.label_82.setObjectName("label_82")
        self.tableWidget_allergies_gs_7 = QtWidgets.QTableWidget(self.widget_18)
        self.tableWidget_allergies_gs_7.setGeometry(QtCore.QRect(160, 40, 161, 391))
        self.tableWidget_allergies_gs_7.setObjectName("tableWidget_allergies_gs_7")
        self.tableWidget_allergies_gs_7.setColumnCount(2)
        self.tableWidget_allergies_gs_7.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_allergies_gs_7.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_allergies_gs_7.setHorizontalHeaderItem(1, item)
        self.label_83 = QtWidgets.QLabel(self.widget_18)
        self.label_83.setGeometry(QtCore.QRect(190, 10, 101, 21))
        self.label_83.setObjectName("label_83")
        self.tableWidget_allergies_ms_7 = QtWidgets.QTableWidget(self.widget_18)
        self.tableWidget_allergies_ms_7.setGeometry(QtCore.QRect(330, 40, 161, 391))
        self.tableWidget_allergies_ms_7.setObjectName("tableWidget_allergies_ms_7")
        self.tableWidget_allergies_ms_7.setColumnCount(2)
        self.tableWidget_allergies_ms_7.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_allergies_ms_7.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_allergies_ms_7.setHorizontalHeaderItem(1, item)
        self.tableWidget_allergies_lgg4_7 = QtWidgets.QTableWidget(self.widget_18)
        self.tableWidget_allergies_lgg4_7.setGeometry(QtCore.QRect(500, 40, 161, 391))
        self.tableWidget_allergies_lgg4_7.setObjectName("tableWidget_allergies_lgg4_7")
        self.tableWidget_allergies_lgg4_7.setColumnCount(2)
        self.tableWidget_allergies_lgg4_7.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_allergies_lgg4_7.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_allergies_lgg4_7.setHorizontalHeaderItem(1, item)
        self.label_84 = QtWidgets.QLabel(self.widget_18)
        self.label_84.setGeometry(QtCore.QRect(360, 10, 101, 21))
        self.label_84.setObjectName("label_84")
        self.label_85 = QtWidgets.QLabel(self.widget_18)
        self.label_85.setGeometry(QtCore.QRect(520, 10, 131, 21))
        self.label_85.setObjectName("label_85")
        self.widget_19 = QtWidgets.QWidget(self.widget)
        self.widget_19.setGeometry(QtCore.QRect(350, 510, 311, 71))
        self.widget_19.setObjectName("widget_19")
        self.btn_back_7 = QtWidgets.QPushButton(self.widget_19)
        self.btn_back_7.setGeometry(QtCore.QRect(10, 20, 101, 31))
        self.btn_back_7.setObjectName("btn_back_7")
        self.btn_save_7 = QtWidgets.QPushButton(self.widget_19)
        self.btn_save_7.setGeometry(QtCore.QRect(110, 20, 101, 31))
        self.btn_save_7.setObjectName("btn_save_7")
        self.btn_save_next_7 = QtWidgets.QPushButton(self.widget_19)
        self.btn_save_next_7.setGeometry(QtCore.QRect(210, 20, 101, 31))
        self.btn_save_next_7.setObjectName("btn_save_next_7")
        self.stackedWidget.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.widget_5 = QtWidgets.QWidget(self.page_8)
        self.widget_5.setGeometry(QtCore.QRect(0, 0, 661, 561))
        self.widget_5.setObjectName("widget_5")
        self.widget_6 = QtWidgets.QWidget(self.widget_5)
        self.widget_6.setGeometry(QtCore.QRect(0, 0, 571, 81))
        self.widget_6.setObjectName("widget_6")
        self.lineEdit_name_8 = QtWidgets.QLineEdit(self.widget_6)
        self.lineEdit_name_8.setGeometry(QtCore.QRect(60, 10, 113, 21))
        self.lineEdit_name_8.setReadOnly(True)
        self.lineEdit_name_8.setObjectName("lineEdit_name_8")
        self.label_25 = QtWidgets.QLabel(self.widget_6)
        self.label_25.setGeometry(QtCore.QRect(30, 10, 60, 16))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.widget_6)
        self.label_26.setGeometry(QtCore.QRect(190, 10, 60, 16))
        self.label_26.setObjectName("label_26")
        self.lineEdit_ID_8 = QtWidgets.QLineEdit(self.widget_6)
        self.lineEdit_ID_8.setGeometry(QtCore.QRect(210, 10, 113, 21))
        self.lineEdit_ID_8.setReadOnly(True)
        self.lineEdit_ID_8.setObjectName("lineEdit_ID_8")
        self.label_43 = QtWidgets.QLabel(self.widget_6)
        self.label_43.setGeometry(QtCore.QRect(330, 10, 60, 21))
        self.label_43.setObjectName("label_43")
        self.lineEdit_age_8 = QtWidgets.QLineEdit(self.widget_6)
        self.lineEdit_age_8.setGeometry(QtCore.QRect(500, 10, 41, 21))
        self.lineEdit_age_8.setReadOnly(True)
        self.lineEdit_age_8.setObjectName("lineEdit_age_8")
        self.lineEdit_weight_8 = QtWidgets.QLineEdit(self.widget_6)
        self.lineEdit_weight_8.setGeometry(QtCore.QRect(460, 40, 51, 21))
        self.lineEdit_weight_8.setReadOnly(True)
        self.lineEdit_weight_8.setObjectName("lineEdit_weight_8")
        self.label_44 = QtWidgets.QLabel(self.widget_6)
        self.label_44.setGeometry(QtCore.QRect(30, 40, 60, 21))
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.widget_6)
        self.label_45.setGeometry(QtCore.QRect(240, 40, 60, 21))
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.widget_6)
        self.label_46.setGeometry(QtCore.QRect(550, 10, 60, 21))
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.widget_6)
        self.label_47.setGeometry(QtCore.QRect(420, 40, 60, 21))
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.widget_6)
        self.label_48.setGeometry(QtCore.QRect(310, 40, 60, 21))
        self.label_48.setObjectName("label_48")
        self.lineEdit_height_8 = QtWidgets.QLineEdit(self.widget_6)
        self.lineEdit_height_8.setGeometry(QtCore.QRect(330, 40, 51, 21))
        self.lineEdit_height_8.setReadOnly(True)
        self.lineEdit_height_8.setObjectName("lineEdit_height_8")
        self.lineEdit_nthVisit_8 = QtWidgets.QLineEdit(self.widget_6)
        self.lineEdit_nthVisit_8.setGeometry(QtCore.QRect(190, 40, 41, 21))
        self.lineEdit_nthVisit_8.setReadOnly(True)
        self.lineEdit_nthVisit_8.setObjectName("lineEdit_nthVisit_8")
        self.lineEdit_birthdate_8 = QtWidgets.QLineEdit(self.widget_6)
        self.lineEdit_birthdate_8.setGeometry(QtCore.QRect(380, 10, 113, 21))
        self.lineEdit_birthdate_8.setReadOnly(True)
        self.lineEdit_birthdate_8.setObjectName("lineEdit_birthdate_8")
        self.lineEdit_lastOfficeVisit_8 = QtWidgets.QLineEdit(self.widget_6)
        self.lineEdit_lastOfficeVisit_8.setGeometry(QtCore.QRect(70, 40, 113, 21))
        self.lineEdit_lastOfficeVisit_8.setReadOnly(True)
        self.lineEdit_lastOfficeVisit_8.setObjectName("lineEdit_lastOfficeVisit_8")
        self.label_74 = QtWidgets.QLabel(self.widget_6)
        self.label_74.setGeometry(QtCore.QRect(380, 40, 60, 21))
        self.label_74.setObjectName("label_74")
        self.label_87 = QtWidgets.QLabel(self.widget_6)
        self.label_87.setGeometry(QtCore.QRect(510, 40, 60, 21))
        self.label_87.setObjectName("label_87")
        self.widget_7 = QtWidgets.QWidget(self.widget_5)
        self.widget_7.setGeometry(QtCore.QRect(0, 80, 661, 431))
        self.widget_7.setObjectName("widget_7")
        self.listWidget_nutrients_8 = QtWidgets.QListWidget(self.widget_7)
        self.listWidget_nutrients_8.setGeometry(QtCore.QRect(10, 30, 256, 391))
        self.listWidget_nutrients_8.setObjectName("listWidget_nutrients_8")
        self.label_49 = QtWidgets.QLabel(self.widget_7)
        self.label_49.setGeometry(QtCore.QRect(110, 10, 60, 21))
        self.label_49.setObjectName("label_49")
        self.tableWidget_RecNut_8 = QtWidgets.QTableWidget(self.widget_7)
        self.tableWidget_RecNut_8.setGeometry(QtCore.QRect(340, 30, 311, 181))
        self.tableWidget_RecNut_8.setObjectName("tableWidget_RecNut_8")
        self.tableWidget_RecNut_8.setColumnCount(2)
        self.tableWidget_RecNut_8.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_RecNut_8.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_RecNut_8.setHorizontalHeaderItem(1, item)
        self.tableWidget_NotRecNut_8 = QtWidgets.QTableWidget(self.widget_7)
        self.tableWidget_NotRecNut_8.setGeometry(QtCore.QRect(340, 240, 311, 181))
        self.tableWidget_NotRecNut_8.setObjectName("tableWidget_NotRecNut_8")
        self.tableWidget_NotRecNut_8.setColumnCount(2)
        self.tableWidget_NotRecNut_8.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_NotRecNut_8.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_NotRecNut_8.setHorizontalHeaderItem(1, item)
        self.label_50 = QtWidgets.QLabel(self.widget_7)
        self.label_50.setGeometry(QtCore.QRect(469, 10, 61, 21))
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.widget_7)
        self.label_51.setGeometry(QtCore.QRect(470, 220, 61, 21))
        self.label_51.setObjectName("label_51")
        self.btn_go2Rec_8 = QtWidgets.QPushButton(self.widget_7)
        self.btn_go2Rec_8.setGeometry(QtCore.QRect(270, 70, 61, 41))
        self.btn_go2Rec_8.setObjectName("btn_go2Rec_8")
        self.btn_undo2Rec_8 = QtWidgets.QPushButton(self.widget_7)
        self.btn_undo2Rec_8.setGeometry(QtCore.QRect(270, 100, 61, 41))
        self.btn_undo2Rec_8.setObjectName("btn_undo2Rec_8")
        self.btn_undo2NotRec_8 = QtWidgets.QPushButton(self.widget_7)
        self.btn_undo2NotRec_8.setGeometry(QtCore.QRect(270, 330, 61, 41))
        self.btn_undo2NotRec_8.setObjectName("btn_undo2NotRec_8")
        self.btn_go2NotRec_8 = QtWidgets.QPushButton(self.widget_7)
        self.btn_go2NotRec_8.setGeometry(QtCore.QRect(270, 300, 61, 41))
        self.btn_go2NotRec_8.setObjectName("btn_go2NotRec_8")
        self.label_52 = QtWidgets.QLabel(self.widget_7)
        self.label_52.setGeometry(QtCore.QRect(280, 150, 60, 21))
        self.label_52.setObjectName("label_52")
        self.radioBtn_lv1_8 = QtWidgets.QRadioButton(self.widget_7)
        self.radioBtn_lv1_8.setGeometry(QtCore.QRect(280, 170, 41, 20))
        self.radioBtn_lv1_8.setChecked(True)
        self.radioBtn_lv1_8.setObjectName("radioBtn_lv1_8")
        self.radioBtn_lv2_8 = QtWidgets.QRadioButton(self.widget_7)
        self.radioBtn_lv2_8.setGeometry(QtCore.QRect(280, 190, 41, 20))
        self.radioBtn_lv2_8.setObjectName("radioBtn_lv2_8")
        self.radioBtn_lv3_8 = QtWidgets.QRadioButton(self.widget_7)
        self.radioBtn_lv3_8.setGeometry(QtCore.QRect(280, 210, 41, 20))
        self.radioBtn_lv3_8.setObjectName("radioBtn_lv3_8")
        self.radioBtn_lv4_8 = QtWidgets.QRadioButton(self.widget_7)
        self.radioBtn_lv4_8.setGeometry(QtCore.QRect(280, 230, 41, 20))
        self.radioBtn_lv4_8.setObjectName("radioBtn_lv4_8")
        self.radioBtn_lv5_8 = QtWidgets.QRadioButton(self.widget_7)
        self.radioBtn_lv5_8.setGeometry(QtCore.QRect(280, 250, 41, 20))
        self.radioBtn_lv5_8.setObjectName("radioBtn_lv5_8")
        self.widget_8 = QtWidgets.QWidget(self.widget_5)
        self.widget_8.setGeometry(QtCore.QRect(280, 520, 371, 41))
        self.widget_8.setObjectName("widget_8")
        self.btn_back_8 = QtWidgets.QPushButton(self.widget_8)
        self.btn_back_8.setGeometry(QtCore.QRect(40, 10, 113, 32))
        self.btn_back_8.setObjectName("btn_back_8")
        self.btn_temp_save_8 = QtWidgets.QPushButton(self.widget_8)
        self.btn_temp_save_8.setGeometry(QtCore.QRect(150, 10, 113, 32))
        self.btn_temp_save_8.setObjectName("btn_temp_save_8")
        self.btn_save_next_8 = QtWidgets.QPushButton(self.widget_8)
        self.btn_save_next_8.setGeometry(QtCore.QRect(260, 10, 113, 32))
        self.btn_save_next_8.setObjectName("btn_save_next_8")
        self.btn_home_8 = QtWidgets.QPushButton(self.widget_5)
        self.btn_home_8.setGeometry(QtCore.QRect(570, 20, 71, 51))
        self.btn_home_8.setObjectName("btn_home_8")
        self.stackedWidget.addWidget(self.page_8)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.btn_home_9 = QtWidgets.QPushButton(self.page_9)
        self.btn_home_9.setGeometry(QtCore.QRect(570, 20, 71, 51))
        self.btn_home_9.setObjectName("btn_home_9")
        self.stackedWidget.addWidget(self.page_9)
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.widget_4 = QtWidgets.QWidget(self.page_10)
        self.widget_4.setGeometry(QtCore.QRect(0, 30, 661, 491))
        self.widget_4.setObjectName("widget_4")
        self.label_54 = QtWidgets.QLabel(self.widget_4)
        self.label_54.setGeometry(QtCore.QRect(50, 430, 60, 16))
        self.label_54.setObjectName("label_54")
        self.radioBtn_upperLevel_auto_10 = QtWidgets.QRadioButton(self.widget_4)
        self.radioBtn_upperLevel_auto_10.setGeometry(QtCore.QRect(140, 460, 100, 20))
        self.radioBtn_upperLevel_auto_10.setChecked(False)
        self.radioBtn_upperLevel_auto_10.setObjectName("radioBtn_upperLevel_auto_10")
        self.radioBtn_upperLevel_manual_10 = QtWidgets.QRadioButton(self.widget_4)
        self.radioBtn_upperLevel_manual_10.setGeometry(QtCore.QRect(200, 460, 100, 20))
        self.radioBtn_upperLevel_manual_10.setObjectName("radioBtn_upperLevel_manual_10")
        self.label_55 = QtWidgets.QLabel(self.widget_4)
        self.label_55.setGeometry(QtCore.QRect(50, 460, 81, 20))
        self.label_55.setObjectName("label_55")
        self.radioBtn_dup_auto_10 = QtWidgets.QRadioButton(self.widget_4)
        self.radioBtn_dup_auto_10.setGeometry(QtCore.QRect(140, 430, 100, 20))
        self.radioBtn_dup_auto_10.setObjectName("radioBtn_dup_auto_10")
        self.radioBtn_dup_manual_10 = QtWidgets.QRadioButton(self.widget_4)
        self.radioBtn_dup_manual_10.setGeometry(QtCore.QRect(200, 430, 100, 20))
        self.radioBtn_dup_manual_10.setObjectName("radioBtn_dup_manual_10")
        self.label_58 = QtWidgets.QLabel(self.widget_4)
        self.label_58.setGeometry(QtCore.QRect(50, 50, 91, 16))
        self.label_58.setObjectName("label_58")
        self.spinBox_printLevel_10 = QtWidgets.QSpinBox(self.widget_4)
        self.spinBox_printLevel_10.setGeometry(QtCore.QRect(150, 50, 48, 24))
        self.spinBox_printLevel_10.setMinimum(1)
        self.spinBox_printLevel_10.setMaximum(5)
        self.spinBox_printLevel_10.setObjectName("spinBox_printLevel_10")
        self.label_59 = QtWidgets.QLabel(self.widget_4)
        self.label_59.setGeometry(QtCore.QRect(50, 80, 111, 20))
        self.label_59.setObjectName("label_59")
        self.ckBox_100gFirst_10 = QtWidgets.QCheckBox(self.widget_4)
        self.ckBox_100gFirst_10.setGeometry(QtCore.QRect(160, 80, 128, 21))
        self.ckBox_100gFirst_10.setChecked(True)
        self.ckBox_100gFirst_10.setObjectName("ckBox_100gFirst_10")
        self.ckBox_onePortionFirst_10 = QtWidgets.QCheckBox(self.widget_4)
        self.ckBox_onePortionFirst_10.setGeometry(QtCore.QRect(280, 80, 128, 21))
        self.ckBox_onePortionFirst_10.setChecked(False)
        self.ckBox_onePortionFirst_10.setObjectName("ckBox_onePortionFirst_10")
        self.ckBox_mortalityFirst_10 = QtWidgets.QCheckBox(self.widget_4)
        self.ckBox_mortalityFirst_10.setGeometry(QtCore.QRect(400, 80, 128, 21))
        self.ckBox_mortalityFirst_10.setChecked(False)
        self.ckBox_mortalityFirst_10.setObjectName("ckBox_mortalityFirst_10")
        self.ckBox_proteinFirst_10 = QtWidgets.QCheckBox(self.widget_4)
        self.ckBox_proteinFirst_10.setGeometry(QtCore.QRect(510, 80, 141, 21))
        self.ckBox_proteinFirst_10.setChecked(False)
        self.ckBox_proteinFirst_10.setObjectName("ckBox_proteinFirst_10")
        self.label_60 = QtWidgets.QLabel(self.widget_4)
        self.label_60.setGeometry(QtCore.QRect(200, 50, 91, 21))
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QLabel(self.widget_4)
        self.label_61.setGeometry(QtCore.QRect(50, 110, 141, 31))
        self.label_61.setObjectName("label_61")
        self.spinBox_allergyGaSungLevel_10 = QtWidgets.QSpinBox(self.widget_4)
        self.spinBox_allergyGaSungLevel_10.setGeometry(QtCore.QRect(180, 110, 48, 31))
        self.spinBox_allergyGaSungLevel_10.setMinimum(0)
        self.spinBox_allergyGaSungLevel_10.setMaximum(5)
        self.spinBox_allergyGaSungLevel_10.setProperty("value", 0)
        self.spinBox_allergyGaSungLevel_10.setObjectName("spinBox_allergyGaSungLevel_10")
        self.label_62 = QtWidgets.QLabel(self.widget_4)
        self.label_62.setGeometry(QtCore.QRect(50, 150, 131, 31))
        self.label_62.setObjectName("label_62")
        self.label_63 = QtWidgets.QLabel(self.widget_4)
        self.label_63.setGeometry(QtCore.QRect(230, 110, 91, 31))
        self.label_63.setObjectName("label_63")
        self.label_65 = QtWidgets.QLabel(self.widget_4)
        self.label_65.setGeometry(QtCore.QRect(50, 190, 171, 31))
        self.label_65.setObjectName("label_65")
        self.label_66 = QtWidgets.QLabel(self.widget_4)
        self.label_66.setGeometry(QtCore.QRect(50, 230, 171, 31))
        self.label_66.setObjectName("label_66")
        self.spinBox_allergyGeupSungLevel_10 = QtWidgets.QSpinBox(self.widget_4)
        self.spinBox_allergyGeupSungLevel_10.setGeometry(QtCore.QRect(180, 150, 48, 31))
        self.spinBox_allergyGeupSungLevel_10.setMinimum(0)
        self.spinBox_allergyGeupSungLevel_10.setMaximum(5)
        self.spinBox_allergyGeupSungLevel_10.setProperty("value", 0)
        self.spinBox_allergyGeupSungLevel_10.setObjectName("spinBox_allergyGeupSungLevel_10")
        self.spinBox_allergyLGG4Level_10 = QtWidgets.QSpinBox(self.widget_4)
        self.spinBox_allergyLGG4Level_10.setGeometry(QtCore.QRect(210, 230, 48, 31))
        self.spinBox_allergyLGG4Level_10.setMinimum(0)
        self.spinBox_allergyLGG4Level_10.setMaximum(5)
        self.spinBox_allergyLGG4Level_10.setProperty("value", 0)
        self.spinBox_allergyLGG4Level_10.setObjectName("spinBox_allergyLGG4Level_10")
        self.spinBox_allergyManSungLevel_10 = QtWidgets.QSpinBox(self.widget_4)
        self.spinBox_allergyManSungLevel_10.setGeometry(QtCore.QRect(180, 190, 48, 31))
        self.spinBox_allergyManSungLevel_10.setMinimum(0)
        self.spinBox_allergyManSungLevel_10.setMaximum(5)
        self.spinBox_allergyManSungLevel_10.setProperty("value", 0)
        self.spinBox_allergyManSungLevel_10.setObjectName("spinBox_allergyManSungLevel_10")
        self.label_69 = QtWidgets.QLabel(self.widget_4)
        self.label_69.setGeometry(QtCore.QRect(50, 350, 51, 21))
        self.label_69.setObjectName("label_69")
        self.label_64 = QtWidgets.QLabel(self.widget_4)
        self.label_64.setGeometry(QtCore.QRect(230, 150, 91, 31))
        self.label_64.setObjectName("label_64")
        self.label_67 = QtWidgets.QLabel(self.widget_4)
        self.label_67.setGeometry(QtCore.QRect(230, 190, 91, 31))
        self.label_67.setObjectName("label_67")
        self.label_68 = QtWidgets.QLabel(self.widget_4)
        self.label_68.setGeometry(QtCore.QRect(260, 230, 91, 31))
        self.label_68.setObjectName("label_68")
        self.label_75 = QtWidgets.QLabel(self.widget_4)
        self.label_75.setGeometry(QtCore.QRect(160, 310, 91, 31))
        self.label_75.setObjectName("label_75")
        self.spinBox_extinctionLevel_10 = QtWidgets.QSpinBox(self.widget_4)
        self.spinBox_extinctionLevel_10.setGeometry(QtCore.QRect(110, 310, 48, 31))
        self.spinBox_extinctionLevel_10.setMinimum(0)
        self.spinBox_extinctionLevel_10.setMaximum(5)
        self.spinBox_extinctionLevel_10.setProperty("value", 0)
        self.spinBox_extinctionLevel_10.setObjectName("spinBox_extinctionLevel_10")
        self.label_76 = QtWidgets.QLabel(self.widget_4)
        self.label_76.setGeometry(QtCore.QRect(50, 310, 111, 31))
        self.label_76.setObjectName("label_76")
        self.toolButton_origin_10 = QtWidgets.QToolButton(self.widget_4)
        self.toolButton_origin_10.setGeometry(QtCore.QRect(100, 350, 91, 22))
        self.toolButton_origin_10.setObjectName("toolButton_origin_10")
        self.label_70 = QtWidgets.QLabel(self.widget_4)
        self.label_70.setGeometry(QtCore.QRect(50, 390, 51, 21))
        self.label_70.setObjectName("label_70")
        self.toolButton_localSpecialty_10 = QtWidgets.QToolButton(self.widget_4)
        self.toolButton_localSpecialty_10.setGeometry(QtCore.QRect(100, 390, 91, 22))
        self.toolButton_localSpecialty_10.setObjectName("toolButton_localSpecialty_10")
        self.widget_11 = QtWidgets.QWidget(self.page_10)
        self.widget_11.setGeometry(QtCore.QRect(300, 520, 371, 41))
        self.widget_11.setObjectName("widget_11")
        self.btn_back_10 = QtWidgets.QPushButton(self.widget_11)
        self.btn_back_10.setGeometry(QtCore.QRect(150, 10, 113, 32))
        self.btn_back_10.setObjectName("btn_back_10")
        self.btn_next_10 = QtWidgets.QPushButton(self.widget_11)
        self.btn_next_10.setGeometry(QtCore.QRect(260, 10, 113, 32))
        self.btn_next_10.setObjectName("btn_next_10")
        self.btn_home_10 = QtWidgets.QPushButton(self.page_10)
        self.btn_home_10.setGeometry(QtCore.QRect(570, 20, 71, 51))
        self.btn_home_10.setObjectName("btn_home_10")
        self.stackedWidget.addWidget(self.page_10)
        self.page_11 = QtWidgets.QWidget()
        self.page_11.setObjectName("page_11")
        self.widget_10 = QtWidgets.QWidget(self.page_11)
        self.widget_10.setGeometry(QtCore.QRect(0, 0, 671, 571))
        self.widget_10.setObjectName("widget_10")
        self.label_71 = QtWidgets.QLabel(self.widget_10)
        self.label_71.setGeometry(QtCore.QRect(40, 30, 151, 16))
        self.label_71.setObjectName("label_71")
        self.label_72 = QtWidgets.QLabel(self.widget_10)
        self.label_72.setGeometry(QtCore.QRect(40, 220, 71, 20))
        self.label_72.setObjectName("label_72")
        self.ckBox_KoreanLang_11 = QtWidgets.QCheckBox(self.widget_10)
        self.ckBox_KoreanLang_11.setGeometry(QtCore.QRect(190, 30, 128, 21))
        self.ckBox_KoreanLang_11.setChecked(True)
        self.ckBox_KoreanLang_11.setObjectName("ckBox_KoreanLang_11")
        self.listWidget_langToPrint_11 = QtWidgets.QListWidget(self.widget_10)
        self.listWidget_langToPrint_11.setGeometry(QtCore.QRect(190, 50, 121, 151))
        self.listWidget_langToPrint_11.setObjectName("listWidget_langToPrint_11")
        self.listWidget_nutrients_11 = QtWidgets.QListWidget(self.widget_10)
        self.listWidget_nutrients_11.setGeometry(QtCore.QRect(110, 250, 211, 251))
        self.listWidget_nutrients_11.setObjectName("listWidget_nutrients_11")
        self.label_77 = QtWidgets.QLabel(self.widget_10)
        self.label_77.setGeometry(QtCore.QRect(190, 230, 71, 20))
        self.label_77.setObjectName("label_77")
        self.listWidget_ingredients_11 = QtWidgets.QListWidget(self.widget_10)
        self.listWidget_ingredients_11.setGeometry(QtCore.QRect(380, 250, 211, 251))
        self.listWidget_ingredients_11.setObjectName("listWidget_ingredients_11")
        self.label_78 = QtWidgets.QLabel(self.widget_10)
        self.label_78.setGeometry(QtCore.QRect(460, 230, 71, 20))
        self.label_78.setObjectName("label_78")
        self.btn_home_11 = QtWidgets.QPushButton(self.widget_10)
        self.btn_home_11.setGeometry(QtCore.QRect(570, 20, 71, 51))
        self.btn_home_11.setObjectName("btn_home_11")
        self.widget_12 = QtWidgets.QWidget(self.widget_10)
        self.widget_12.setGeometry(QtCore.QRect(300, 520, 371, 41))
        self.widget_12.setObjectName("widget_12")
        self.btn_back_11 = QtWidgets.QPushButton(self.widget_12)
        self.btn_back_11.setGeometry(QtCore.QRect(150, 10, 113, 32))
        self.btn_back_11.setObjectName("btn_back_11")
        self.btn_next_11 = QtWidgets.QPushButton(self.widget_12)
        self.btn_next_11.setGeometry(QtCore.QRect(260, 10, 113, 32))
        self.btn_next_11.setObjectName("btn_next_11")
        self.label_57 = QtWidgets.QLabel(self.widget_10)
        self.label_57.setGeometry(QtCore.QRect(80, 200, 91, 20))
        self.label_57.setObjectName("label_57")
        self.radioBtn_RDA_11 = QtWidgets.QRadioButton(self.widget_10)
        self.radioBtn_RDA_11.setGeometry(QtCore.QRect(170, 200, 131, 20))
        self.radioBtn_RDA_11.setChecked(True)
        self.radioBtn_RDA_11.setObjectName("radioBtn_RDA_11")
        self.radioButton_WHO_11 = QtWidgets.QRadioButton(self.widget_10)
        self.radioButton_WHO_11.setGeometry(QtCore.QRect(300, 200, 131, 20))
        self.radioButton_WHO_11.setObjectName("radioButton_WHO_11")
        self.radioButton_MFDS_11 = QtWidgets.QRadioButton(self.widget_10)
        self.radioButton_MFDS_11.setGeometry(QtCore.QRect(440, 200, 131, 20))
        self.radioButton_MFDS_11.setObjectName("radioButton_MFDS_11")
        self.stackedWidget.addWidget(self.page_11)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 721, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.setupFlow()

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def setupFlow(self):
        # page 1
        self.btn_enter_0.clicked.connect(self.checkPwd)
        # page 2
        self.btn_go2Client_1.clicked.connect(self.go2Client)
        self.btn_go2Data_1.clicked.connect(self.go2Data)
        self.btn_logout_1.clicked.connect(self.logout)
        # page 3
        self.btn_findExistingClient_2.clicked.connect(self.go2FindExistingClient)
        self.btn_registerNewClient_2.clicked.connect(self.go2RegisterNewClientPage1)
        self.btn_home_2.clicked.connect(self.goHome)
        # page 4_1 - register new client page 1
        self.btn_home_3.clicked.connect(self.goHomeFromPage3)
        self.btn_cancel_3.clicked.connect(self.cancelRegisterNewClient)
        self.btn_next_3.clicked.connect(self.go2RegisterNewClientPage2)
        # page 4_1_1 register new client page 2
        self.btn_cancel_4.clicked.connect(self.cancelRegisterNewClient)
        self.btn_back_4.clicked.connect(self.go2RegisterNewClientPage1)
        # page_5 - find existing client
        self.btn_cancel_5.clicked.connect(self.cancelFindExistingClient)
        self.btn_home_5.clicked.connect(self.goHomeFromPage5)

    def goHomeFromPage5(self):
        self.clearFindExistingClient()
        self.goHome()

    def go2RegisterNewClientPage2(self):
        tempID = self.lineEdit_ID_3.text()
        tempName = self.lineEdit_name_3.text()

        if len(tempID) == 0 or len(tempName) == 0:
            msgbox = QtWidgets.QMessageBox()
            msgbox.setIcon(QtWidgets.QMessageBox.Warning)
            msgbox.setText("ID, 이름, 생년월일은 필수입니다.")
            msgbox.setWindowTitle("Error")
            msgbox.exec_()
        else:
            self.stackedWidget.setCurrentIndex(4)

            myCursor_dis = get_all_diseases()
            create_checkbox_lw(myCursor_dis, self.listWidget_diseases_4, '질병명',  True, None)
            # for dis in myCursor_dis:
            #     ckbtnitem = QtWidgets.QListWidgetItem(dis["질병명"])
            #     ckbtnitem.setFlags(QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
            #     ckbtnitem.setCheckState(QtCore.Qt.Unchecked)
            #     self.listWidget_diseases_4.addItem(ckbtnitem)

            myCursor_gs = get_ingredients_guepsung()
            create_checkbox_level_tw(myCursor_gs, self.tableWidget_allergies_gs_4, "식품명", True, None)
            myCursor_ms = get_ingredients_mansung()
            create_checkbox_level_tw(myCursor_ms, self.tableWidget_allergies_ms_4, "식품명", True, None)
            myCursor_lgg4 = get_ingredients_mansung_lgg4()
            create_checkbox_level_tw(myCursor_lgg4, self.tableWidget_allergies_lgg4_4, "식품명", True, None)


    def clearFindExistingClient(self):
        self.lineEdit_ID_5.setText("")
        self.lineEdit_name_5.setText("")
        self.tableWidget_clientCandidates_5.setRowCount(0)

    def cancelFindExistingClient(self):
        self.clearFindExistingClient()
        self.go2PreviousPage(3)

    def goHomeFromPage3(self):
        if self.warnBeforeHome() == False:
            return
        else:
            self.clearRegisterNewClient()
            self.goHome()

    def warnBeforeHome(self):
        msgbox = QtWidgets.QMessageBox()
        msgbox.setWindowTitle("Warning")
        msgbox.setText("현재 페이지 정보가 사라집니다. 홈으로 이동하시겠습니까?")
        msgbox.setStandardButtons(QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No)
        msgbox.setDefaultButton(QtWidgets.QMessageBox.No)
        ret = msgbox.exec_()
        if ret == QtWidgets.QMessageBox.Yes:
            return True
        else:
            return False

    def clearRegisterNewClient(self):
        self.lineEdit_ID_3.setText("")
        self.lineEdit_name_3.setText("")
        self.radioBtn_male_3.setChecked(True)
        self.radioBtn_female_3.setChecked(False)
        self.dateEdit_birthdate_3.setDate(QtCore.QDate(1900, 1, 1))
        self.lineEdit_address_3.setText("")
        self.lineEdit_height_3.setText("")
        self.lineEdit_weight_3.setText("")
        self.ckBox_preg_3.setChecked(False)
        self.ckBox_bFeeding_3.setChecked(False)
        self.dateEdit_lastOfficeVisit_3.setDate(QtCore.QDate.currentDate())
        for index in range(self.listWidget_diseases_4.count()):
            self.listWidget_diseases_4.item(index).setCheckState(QtCore.Qt.Unchecked)

    def cancelRegisterNewClient(self):
        self.clearRegisterNewClient()
        self.go2PreviousPage(3)

    def go2PreviousPage(self, currPage):
        self.stackedWidget.setCurrentIndex(currPage - 1)

    def logout(self):
        self.stackedWidget.setCurrentIndex(0)

    def goHome(self):
        self.stackedWidget.setCurrentIndex(1)

    def go2FindExistingClient(self):
        self.stackedWidget.setCurrentIndex(5)
        # self.lineEdit_ID_5.setText("")
        # self.lineEdit_name_5.setText("")

    def go2RegisterNewClientPage1(self):
        self.stackedWidget.setCurrentIndex(3)

    #############################
    # TODO - NEED TO WORK ON DATA PAGE
    #############################
    def updatePatients(self):
        # for patient in getAllPatients():
        #     self.tableWidget_clientCandidates_5.
        #     patient.
        pass

    def go2Data(self):
        pass

    def go2Client(self):
        self.stackedWidget.setCurrentIndex(2)

    def checkPwd(self):
        pwd = self.lineEdit_pw_0.text()
        if pwd == "kiho":
            self.lineEdit_pw_0.setText("")
            self.stackedWidget.setCurrentIndex(1)
        elif len(pwd) != 0:
            msgbox = QtWidgets.QMessageBox()
            msgbox.setIcon(QtWidgets.QMessageBox.Warning)
            msgbox.setText("Incorrect Password")
            msgbox.setWindowTitle("Error")
            msgbox.exec_()
        else:
            msgbox = QtWidgets.QMessageBox()
            msgbox.setIcon(QtWidgets.QMessageBox.Warning)
            msgbox.setText("Please enter password")
            msgbox.setWindowTitle("Error")
            msgbox.exec_()


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "비밀번호:"))
        self.btn_enter_0.setText(_translate("MainWindow", "Enter"))
        self.btn_go2Data_1.setText(_translate("MainWindow", "데이터 수정"))
        self.btn_go2Client_1.setText(_translate("MainWindow", "환자 보기"))
        self.btn_logout_1.setText(_translate("MainWindow", "로그아웃"))
        self.btn_registerNewClient_2.setText(_translate("MainWindow", "신규 회원 등록"))
        self.btn_findExistingClient_2.setText(_translate("MainWindow", "기존 회원 찾기"))
        self.label.setText(_translate("MainWindow", "환자 정보"))
        self.btn_home_2.setText(_translate("MainWindow", "HOME"))
        self.label_3.setText(_translate("MainWindow", "신규 회원 등록"))
        self.label_4.setText(_translate("MainWindow", "ID"))
        self.label_5.setText(_translate("MainWindow", "이름"))
        self.label_6.setText(_translate("MainWindow", "성별"))
        self.label_7.setText(_translate("MainWindow", "생년월일"))
        self.label_8.setText(_translate("MainWindow", "주소"))
        self.label_10.setText(_translate("MainWindow", "진료일"))
        self.label_11.setText(_translate("MainWindow", "키"))
        self.label_12.setText(_translate("MainWindow", "몸무게"))
        self.ckBox_preg_3.setText(_translate("MainWindow", "임신"))
        self.ckBox_bFeeding_3.setText(_translate("MainWindow", "수유"))
        self.radioBtn_female_3.setText(_translate("MainWindow", "여"))
        self.radioBtn_male_3.setText(_translate("MainWindow", "남"))
        self.dateEdit_birthdate_3.setDisplayFormat(_translate("MainWindow", "yyyy/M/d"))
        self.dateEdit_lastOfficeVisit_3.setDisplayFormat(_translate("MainWindow", "yyyy/M/d"))
        self.btn_home_3.setText(_translate("MainWindow", "HOME"))
        self.btn_cancel_3.setText(_translate("MainWindow", "취소"))
        self.btn_next_3.setText(_translate("MainWindow", "다음"))
        self.btn_checkUniqID_3.setText(_translate("MainWindow", "ID 사용가능?"))
        self.label_13.setText(_translate("MainWindow", "kg"))
        self.label_24.setText(_translate("MainWindow", "cm"))
        self.label_34.setText(_translate("MainWindow", "질병"))
        item = self.tableWidget_allergies_gs_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "식재료"))
        item = self.tableWidget_allergies_gs_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "알레르기 레벨"))
        self.label_53.setText(_translate("MainWindow", "급성 알레르기 음식"))
        item = self.tableWidget_allergies_ms_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "식재료"))
        item = self.tableWidget_allergies_ms_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "알레르기 레벨"))
        item = self.tableWidget_allergies_lgg4_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "식재료"))
        item = self.tableWidget_allergies_lgg4_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "알레르기 레벨"))
        self.label_80.setText(_translate("MainWindow", "만성 알레르기 음식"))
        self.label_81.setText(_translate("MainWindow", "만성 알레르기 lgG4 음식 "))
        self.btn_cancel_4.setText(_translate("MainWindow", "취소"))
        self.btn_registerClient_4.setText(_translate("MainWindow", "등록"))
        self.btn_back_4.setText(_translate("MainWindow", "뒤로"))
        self.label_38.setText(_translate("MainWindow", "기존회원 찾기 "))
        self.label_27.setText(_translate("MainWindow", "ID로 찾기"))
        self.btn_findbyID_5.setText(_translate("MainWindow", "찾기"))
        self.label_30.setText(_translate("MainWindow", "회원이름으로 찾기"))
        self.btn_findbyName_5.setText(_translate("MainWindow", "찾기"))
        item = self.tableWidget_clientCandidates_5.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_clientCandidates_5.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "이름"))
        item = self.tableWidget_clientCandidates_5.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "생년월일"))
        item = self.tableWidget_clientCandidates_5.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "주소"))
        self.btn_home_5.setText(_translate("MainWindow", "HOME"))
        self.btn_cancel_5.setText(_translate("MainWindow", "취소"))
        self.btn_confirmClient_5.setText(_translate("MainWindow", "확인"))
        self.label_31.setText(_translate("MainWindow", "기존 회원 정보 보기/수정"))
        self.label_32.setText(_translate("MainWindow", "주소"))
        self.label_41.setText(_translate("MainWindow", "진료일"))
        self.radioBtn_female_6.setText(_translate("MainWindow", "여"))
        self.label_37.setText(_translate("MainWindow", "키"))
        self.radioBtn_male_6.setText(_translate("MainWindow", "남"))
        self.label_39.setText(_translate("MainWindow", "이름"))
        self.dateEdit_lastOfficeVisit_6.setDisplayFormat(_translate("MainWindow", "yyyy/M/d"))
        self.ckBox_preg_6.setText(_translate("MainWindow", "임신"))
        self.ckBox_bFeeding_6.setText(_translate("MainWindow", "수유"))
        self.label_40.setText(_translate("MainWindow", "생년월일"))
        self.dateEdit_birthdate_6.setDisplayFormat(_translate("MainWindow", "yyyy/M/d"))
        self.label_36.setText(_translate("MainWindow", "ID"))
        self.label_35.setText(_translate("MainWindow", "몸무게"))
        self.label_42.setText(_translate("MainWindow", "성별"))
        self.btn_home_6.setText(_translate("MainWindow", "HOME"))
        self.btn_cancel_6.setText(_translate("MainWindow", "취소"))
        self.btn_save_6.setText(_translate("MainWindow", "저장"))
        self.btn_save_next_6.setText(_translate("MainWindow", "저장 후 다음"))
        self.label_56.setText(_translate("MainWindow", "cm"))
        self.label_79.setText(_translate("MainWindow", "kg"))
        self.label_14.setText(_translate("MainWindow", "이름"))
        self.label_15.setText(_translate("MainWindow", "ID"))
        self.label_16.setText(_translate("MainWindow", "생년월일 "))
        self.label_17.setText(_translate("MainWindow", "진료일"))
        self.label_18.setText(_translate("MainWindow", "번째 방문"))
        self.label_19.setText(_translate("MainWindow", "세"))
        self.label_20.setText(_translate("MainWindow", "몸무게"))
        self.label_21.setText(_translate("MainWindow", "키"))
        self.label_73.setText(_translate("MainWindow", "cm"))
        self.label_86.setText(_translate("MainWindow", "kg"))
        self.btn_home_7.setText(_translate("MainWindow", "HOME"))
        self.label_82.setText(_translate("MainWindow", "질병"))
        item = self.tableWidget_allergies_gs_7.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "식재료"))
        item = self.tableWidget_allergies_gs_7.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "알레르기 레벨"))
        self.label_83.setText(_translate("MainWindow", "급성 알레르기 음식"))
        item = self.tableWidget_allergies_ms_7.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "식재료"))
        item = self.tableWidget_allergies_ms_7.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "알레르기 레벨"))
        item = self.tableWidget_allergies_lgg4_7.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "식재료"))
        item = self.tableWidget_allergies_lgg4_7.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "알레르기 레벨"))
        self.label_84.setText(_translate("MainWindow", "만성 알레르기 음식"))
        self.label_85.setText(_translate("MainWindow", "만성 알레르기 lgG4 음식 "))
        self.btn_back_7.setText(_translate("MainWindow", "뒤로"))
        self.btn_save_7.setText(_translate("MainWindow", "저장"))
        self.btn_save_next_7.setText(_translate("MainWindow", "저장 후 다음"))
        self.label_25.setText(_translate("MainWindow", "이름"))
        self.label_26.setText(_translate("MainWindow", "ID"))
        self.label_43.setText(_translate("MainWindow", "생년월일 "))
        self.label_44.setText(_translate("MainWindow", "진료일"))
        self.label_45.setText(_translate("MainWindow", "번째 방문"))
        self.label_46.setText(_translate("MainWindow", "세"))
        self.label_47.setText(_translate("MainWindow", "몸무게"))
        self.label_48.setText(_translate("MainWindow", "키"))
        self.label_74.setText(_translate("MainWindow", "cm"))
        self.label_87.setText(_translate("MainWindow", "kg"))
        self.label_49.setText(_translate("MainWindow", "영양소"))
        item = self.tableWidget_RecNut_8.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "영양소"))
        item = self.tableWidget_RecNut_8.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "레벨"))
        item = self.tableWidget_NotRecNut_8.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "영양소"))
        item = self.tableWidget_NotRecNut_8.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "레벨"))
        self.label_50.setText(_translate("MainWindow", "권고 영양소"))
        self.label_51.setText(_translate("MainWindow", "주의 영양소"))
        self.btn_go2Rec_8.setText(_translate("MainWindow", "->"))
        self.btn_undo2Rec_8.setText(_translate("MainWindow", "<-"))
        self.btn_undo2NotRec_8.setText(_translate("MainWindow", "<-"))
        self.btn_go2NotRec_8.setText(_translate("MainWindow", "->"))
        self.label_52.setText(_translate("MainWindow", "Level"))
        self.radioBtn_lv1_8.setText(_translate("MainWindow", "1"))
        self.radioBtn_lv2_8.setText(_translate("MainWindow", "2"))
        self.radioBtn_lv3_8.setText(_translate("MainWindow", "3"))
        self.radioBtn_lv4_8.setText(_translate("MainWindow", "4"))
        self.radioBtn_lv5_8.setText(_translate("MainWindow", "5"))
        self.btn_back_8.setText(_translate("MainWindow", "뒤로"))
        self.btn_temp_save_8.setText(_translate("MainWindow", "임시저장"))
        self.btn_save_next_8.setText(_translate("MainWindow", "저장 후 다음"))
        self.btn_home_8.setText(_translate("MainWindow", "HOME"))
        self.btn_home_9.setText(_translate("MainWindow", "HOME"))
        self.label_54.setText(_translate("MainWindow", "중복 제거:"))
        self.radioBtn_upperLevel_auto_10.setText(_translate("MainWindow", "자동"))
        self.radioBtn_upperLevel_manual_10.setText(_translate("MainWindow", "수동"))
        self.label_55.setText(_translate("MainWindow", "상위레벨 유지: "))
        self.radioBtn_dup_auto_10.setText(_translate("MainWindow", "자동"))
        self.radioBtn_dup_manual_10.setText(_translate("MainWindow", "수동"))
        self.label_58.setText(_translate("MainWindow", "출력대표성 등급:"))
        self.label_59.setText(_translate("MainWindow", "1회 분량당 출력조건:"))
        self.ckBox_100gFirst_10.setText(_translate("MainWindow", "100g당 많은 순서"))
        self.ckBox_onePortionFirst_10.setText(_translate("MainWindow", "1회분량 고려출력"))
        self.ckBox_mortalityFirst_10.setText(_translate("MainWindow", "폐기율 고려출력"))
        self.ckBox_proteinFirst_10.setText(_translate("MainWindow", "단백질가식부 고려출력"))
        self.label_60.setText(_translate("MainWindow", "등급 이하 출력"))
        self.label_61.setText(_translate("MainWindow", "가성알레르기 해당식품:"))
        self.label_62.setText(_translate("MainWindow", "급성알레르기 유발등급:"))
        self.label_63.setText(_translate("MainWindow", "등급 이상 제외"))
        self.label_65.setText(_translate("MainWindow", "만성알레르기 유발등급:"))
        self.label_66.setText(_translate("MainWindow", "만성lgG4 과민반응 유발등급:"))
        self.label_69.setText(_translate("MainWindow", "원산지:"))
        self.label_64.setText(_translate("MainWindow", "등급 이상 제외"))
        self.label_67.setText(_translate("MainWindow", "등급 이상 제외"))
        self.label_68.setText(_translate("MainWindow", "등급 이상 제외"))
        self.label_75.setText(_translate("MainWindow", "등급 이상 제외"))
        self.label_76.setText(_translate("MainWindow", "멸종등급:"))
        self.toolButton_origin_10.setText(_translate("MainWindow", "..."))
        self.label_70.setText(_translate("MainWindow", "특산지:"))
        self.toolButton_localSpecialty_10.setText(_translate("MainWindow", "..."))
        self.btn_back_10.setText(_translate("MainWindow", "뒤로"))
        self.btn_next_10.setText(_translate("MainWindow", "다음"))
        self.btn_home_10.setText(_translate("MainWindow", "HOME"))
        self.label_71.setText(_translate("MainWindow", "식재료/성분 출력 언어표시:"))
        self.label_72.setText(_translate("MainWindow", "출력할 내용:"))
        self.ckBox_KoreanLang_11.setText(_translate("MainWindow", "한국어"))
        self.label_77.setText(_translate("MainWindow", "영양소 관련"))
        self.label_78.setText(_translate("MainWindow", "식재료 관련"))
        self.btn_home_11.setText(_translate("MainWindow", "HOME"))
        self.btn_back_11.setText(_translate("MainWindow", "뒤로"))
        self.btn_next_11.setText(_translate("MainWindow", "다음"))
        self.label_57.setText(_translate("MainWindow", "성분계산단위:"))
        self.radioBtn_RDA_11.setText(_translate("MainWindow", "하루 권장량 (RDA)"))
        self.radioButton_WHO_11.setText(_translate("MainWindow", "최대 권장량 (WHO)"))
        self.radioButton_MFDS_11.setText(_translate("MainWindow", "최대 권장량 (식약처)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = UI()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

